name: 'Setup Node.js'
description: 'Sets up Node.js with caching'

inputs:
  cache-path:
    description: 'Path to package-lock.json for cache'
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: ${{ inputs.cache-path }} 