name: 'Setup AWS and Terraform'
description: 'Configures AWS credentials and Terraform'

inputs:
  aws-access-key-id:
    description: 'AWS access key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: true
  aws-region:
    description: 'AWS region'
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Cache Terraform
      uses: actions/cache@v3
      with:
        path: .terraform
        key: terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
        restore-keys: |
          terraform- 